### ISSUE TITLE
对成绩的描述

### ISSUE THREAD

**Issue by LuminousXLB** [SurviveSJTU/SurviveSJTUManual#10]
## 原文如下

GPA制度概览

> 大部分大三以前的学生没见过成绩单的模样，我们可以先给你描述一 下。成绩单就是一张纸，上面记录了你四年来修的所有课程及分数。成 绩单上不计算 GPA 和排名，学校也明确声明不负责计算学生的 GPA 和排名。而实际上，最终我们常说的那个 GPA ，实际上是自己计算出来的 Overall GPA ，也就是把所有的课加权平均后计算得到的数字。也许我们中有人听说过“ Major GPA ”之类的概念，但是这里必须澄清，目前任何对于 Major GPA 的定义都是非官方的，全凭自己说了算。所以，最有公信力的 GPA 衡量指标，只是一个加权和！当你填表的时候，能有一个很高的 GPA ，那么你的优势就已经建立了。所谓 GPA 低而 Major GPA 高好像意味着专业基本功扎实之类的话，那都是失败者们自己给自己找的借 口而已。

## 建议改为

大部分大三以前的学生没见过成绩单的模样，到新行政楼一楼5元钱就可以打印一张。我们可以先给你描述一下，成绩单就是一张纸，上面记录了你四年来修的所有课程及分数（可以选择百分制和等级制）。成绩单上不计算平均学积分、平均绩点和排名，但是教学信息服务网上可以查到，如果需要证明可以到学院教务办开具。
平均学积分是百分制的，平均绩点是4.3分制的。两个指标都有“全部课程”和“核心课程”的差别。但是核心课程是包含了两课等公共必修课的，所以虽然是排除了通识课和个性化修读课程的影响，但是仍然不能完全代表专业基本功。

**Comment by brucechin** [comment]
本段当时的作者个人色彩的确过于浓厚，之后会做小修，谢谢！

**Comment by LuminousXLB** [comment]
倒不是觉得个人色彩浓厚，而是有些信息已经过时了
