### ISSUE TITLE
上海交大转专业指南

### ISSUE THREAD

**Issue by dujiajun** [SurviveSJTU/SurviveSJTUManual#20]
# 上海交大转专业指南

> 成文时间：2020年4月25日

上海交大转专业是怎么回事呢？上海交大相信大家都很熟悉，但是上海交大转专业是怎么回事呢，下面就让小编带大家一起了解吧。

## 一、学生手册相关政策

根据《上海交通大学本科生管理规定》（沪交教〔2019〕42号）第二十四条至第二十八条规定，在上海交大转专业的条件需要满足以下之一：

1. 学生确有专长；
2. 符合自主转专业有关要求；
3. 生理原因；
4. 学校调整专业；
5. 未有特殊限制的休学创业复学学生；
6. 未有特殊限制的参军退役复学学生。

除此之外，还有一些限制条件，有下列情况之一的不予转专业：

1. 新生入学未满一年或本科三年级（含）以上；
2. 特殊招生形式录取的；
3. 和学校有特殊约定的；
4. 已经有过转专业的；
5. 其他无正当原因的

现在交大招生录取分了各种渠道：普通入学、自主招生、高校专项（思源计划）、综合评价（上海、浙江）、贫困专项、高水平艺术团、保送、提前批（工科、自科、农学、核工、外语）、设计类、预科、内地班，等等。不同的入学方式在转专业上有不同的条件、限制、时间、流程。下面笔者将根据所了解到的情况，对部分情况的转专业进行讲解。

## 二、自主转专业

大家一般指的转专业，也就是大一下的自主转专业，这只是学生手册中转专业条件的第二条，不包含其他情况。自主转专业一般在大一下学期4月份，比如笔者写这篇文章的时候就是2019级本科生自主转专业的时候了。

### （一）面向群体

根据《上海交通大学2019级本科生自主调整专业类别实施办法》，

>  视觉传达设计专业、提前批次录取学生、非2019年入学的学生、不符合各学院自主调整专业类别要求的学生以及与学校签订有关协议的学生不参与本次自主调整专业类别工作。外语类保送生仅可在英语、日语、德语、法语等外语类专业间调整专业。外语类保送生仅可在英语、日语、德语、法语等外语类专业间调整专业。港澳台学生仅可在本地区招生专业目录范围内调整专业。对于2019年入学的内地班及预科转正学生，允许在同年（2019年）同一录取方式可录取的专业范围内申请转专业，具体可参照内地班及预科转正专业类表所示。

也就是说，普通高考、自主招生、高校专项（思源计划）、贫困专项、综合评价（不含工科试验班）等方式入学的学生，可以完全参与此次自主转专业。而外语类、内地班预科班等存在专业限制。其他方式（自科、工科试验班等）不参与自主转专业流程。

### （二）条件

《办法》中同样写明了自主转专业的条件：

1. 完成原学院执行计划课程要求（允许已修读课程中有1门课程不及格），符合拟转入学院的相关条件。
2. 未受过校纪校规处分及退学警告，无违纪违规行为。

仅从这个条件来说，转专业的限制是非常宽松的。但是要注意几点：

第一，几乎所有院系，特别是热门专业所在的院系，还给出了自己的招收条件。比如材料、船建、机动、电院等要求无不及格记录，IEEE试点班和AI试点班只能相互之间转，数学要求数学成绩平均70分以上，经管试验班要求专业核心学积分在前40%以内等等。所以在考虑转专业的时候，不只是考虑教务处文件中的基本要求，还得考虑转入院系的招收条件。

第二，教务处的通知一般会写出院系的招收名额和条件，但是这个一般针对全院。对于电院这种规模大、专业多的学院，很可能会针对不同专业划分更细的名额，提出更高的要求。比如电院本教办网站就挂出了《电子信息与电气工程学院关于2019级自主调整专业工作的补充通知》，通知中明确写道：

> 计算机科学与技术、软件工程、信息安全、人工智能专业、IEEE试点班仅接收第一志愿填报的学生进行考察。

第三，院系的招收条件很可能每年情况不一样。不要想着自己满足了去年的条件，今年就一定满足条件。

第四，不同专业可能对第一志愿和第二志愿条件不同，对第二志愿要求更高。因此需要填报志愿的时候合理选择顺序。

第五，部分包含多个专业的学院，对于外院转入和本院内部转专业的名额或者条件是不同的，很可能外院转入名额比院内转名额更多。

第六，少部分院系对于申请转出有自己的限制。比如农生学院对于贫困专项计划学生申请转出要求无不及格课程，第一学期核心课程学积分专业排名前15%。

### （三）流程

自己填写申请表（一志愿和二志愿）--> 院系考核（笔试/机考或者面试，或者均有）--> 教务处审核 --> 公示名单 --> 确认新的培养计划 --> 新学期复核。

自主转专业通知每年都会按时挂在教务处官网上，而院系、班群、思政等可能不会主动通知学生。因此对于想转专业的同学，需要主动关注这个消息，以免错过时间。

值得注意的地方是，这里的一志愿和二志愿并非平行志愿，院系在考核的时候知道学生把它们当做第几志愿。因此若是第二志愿填报的专业，院系在考核中可能会询问到为什么把他们放到第二志愿。

若是第二学期转成专业，但是当学期出现挂科（含选修课）情况，仍然将会被退回原专业。所以若是转成功专业，切不可当学期就放飞自我，千万不要挂科。

### （四）奖学金

根据《上海交通大学奖学金评选管理办法》（沪交学〔2017〕35号）第十三条规定，转专业的学生不参与原学院（系）的专项奖学金评选，其他类别奖学金仍然原学院（系）评选。这里的其他类别奖学金包括国家奖学金，上海市奖学金，校级优秀奖学金等等。

## 三、自科、工科平台分流

自科、工科平台是学校在提前批（上海生源仍然按照提前批执行）招生的专业，因此不符合上文提到的自主转专业要求。但是并非不可以转专业，而是在平台内分流。

这里就要提到“**分流**”这个词语了。以普通高考方式入学的大类招生，会把分专业和转专业称作“分流”和“转专业”。而对于自科、工科平台，分专业和转专业分别被称为“专业预选”和“专业分流”，转专业将仅能转平台内存在的专业，不能转出平台。

这个称呼是怎么来的呢？在工科平台前几届中，考虑平台培养，前三学期大家都是“工科平台”专业，只有第四学期开始会进入到专业学习，所以第三学期才叫“**分流**”。由于学校的奇葩想法，第一学期就在着手分专业的事情，但是又由于大家专业还是”工科平台“，于是第一学期那个叫做“**预选**”。但是对于2018级起的学生，在“预选”后第2学期起，大家已经进入到不同专业进行学习，教务系统中的专业名称也为细分专业，“工科平台”已经不存在了。所以这时起，“预选”和“分流”就有点名不副实，仅仅是沿用了过去的说法而已。在下面的介绍中，如无特殊说明，自科、工科平台的“分流”和“转专业”是等价的概念。

工科平台的分流时间一直在大二上学期的10月份左右。而近几年的自科平台分流时间有所变化，从早几届的大一下学期3月份变成了18级的大二上学期10月份。因为笔者对工科平台更熟，以下内容全部以工科平台举例。

### （一）条件

教务处给出的申请条件非常宽松，为如下两点：

1. 入校后未受过校纪校规处分，无违纪违规行为，未受过退学警告；
2. 大一第一学年必须修完执行计划中的必修课程，且所修所有课程无不及格。

在自主转专业中提到的几点注意，大部分在这里同样适用。举几个例子。

第二点提到的部分专业仅接受第一志愿。比如2018级分流中，计算机科学与技术、软件工程、信息安全专业仅接收第一志愿填报的学生参加考察。

第三点谈到条件可能每年变化。比如2015级分流中，计算机接收条件中提到

> 非预选至电院的学生且《程序设计思想与方法》课程成绩在95分及以上可考虑破格进入面试

而在之后几年的分流考核中，不再具有这一条备注。

第四点谈到部分专业对第一志愿和第二志愿要求不同。比如2018级分流中，自动化专业的要求为

> 院外学生：第一志愿：排名百分比前35%； 第二志愿：排名百分比前10%。
>
> 院内学生：第一志愿：排名百分比前20%； 第二志愿：排名百分比前5%。

第五点谈到部分学院对院外院内转专业区分对待。上一条自动化是一个例子。工科平台分流中，电院对于外院转入和院内转的名额分配存在和自主转专业一样的情况，也就是院外名额比院内多，只是工科平台分流的时候没有明确写出来而已。

除了自主转专业中的几点注意之外，工科平台分流的时候还存在一个非常大的问题。部分学院可能在志愿填报结束之后才公布他们的招收条件和考核方案。

举两个例子，在2017级分流中，志愿填报截止时间是10月7日，而在一周以后的10月16日，电院公布软件工程，计算机和信息安全仅接受第一志愿填报的学生。而以往年级中并无此条件，导致部分同学预估失误。在2018级分流中，教务处要求学生在10月8日之前完成志愿填报。而在填报结束4天之后的10月12日，电院自动化公布了面试入围资格（上文已经给出），而往年无这条要求。那么如果一些同学没有达到这个专业的入围资格，但是理论上可以去其他专业面试，仅仅因为申请结束之后才公布面试入围资格，他们就没有能够利用好这次转专业的机会，非常可惜。

### （二）流程

流程和自主转专业非常类似，在此不再赘述。注意在线填报的入口和自主转专业不同。

### （三）关于30%

在自科、工科平台分流通知中有这样一句话：

> 转出学院应严格保证各专业**转出数量不超过预选人数的30%**。

这句话对于很多同学产生了一定的误解，他们认为只有专业前30%才可以申请转专业。事实上，这个要求指的是，每个专业最多30%的同学转出，而不是前30%的同学才能转。若是一个专业排名前30%的同学没有全部申请转专业，那么这个名额限制就往后顺移。

很多同学在大一上刚预选专业后就觉得自己所在的专业没有前途了，想大二转专业。而到了大二上，申请转专业的同学往往没有那么多，很多人就是在一个地方待了一年多感觉熟悉了、习惯了，就不想转专业了。所以实际上想转的人没有那么多，大多数专业转出都不会被30%的名额卡住。

另外需要注意的是这个30%名额限制指的是细分的小专业，而不是所在的学院。假设大一分到了交通运输这个只有15个人的专业，那么这个专业就得限制不超过4.5个人转出，也就是最多转出4个人。

### （四）课程补修问题

对于自主转专业的同学来说，他们在大一下就转专业了，补修的内容比较少，而且培养计划差异大的情况下，他们可以选择降级。对于工科平台分流的东西，在大二上转专业就面临着培养计划差异大的情况，而且没有办法选择降级。

因为平台化培养，本来这一项问题在工科平台最开始几届问题并不突出。比如2016级分流中，如果一个电院外的同学转入计算机专业，那么他只需要补修离散数学、数据结构、工程实践电类等三门课。但是从2018级开始，由于大一下和大二上就已经按照不同专业进行上课了，当大二上转专业的时候，培养计划差异就很明显。比如2018级分流中，如果一个电院外的同学转入信息安全专业，那么他需要补修大一下的工科创1，大二上的离散数学、数电、模电、电子技术实验，一共5门课。虽然电院为这部分同学在大二下开设了4门课的补修专门班，但是他们很可能因为其他课程冲突的原因补修不了。假设完全不冲突的话，这位转入信息安全专业的同学在大二下就要补修5门课，加上正常的8门必修课，一共13门课，这学期就会非常难过。

注意，希望保研的同学需要在大三下结束的时候补修完培养计划中的所有课程，以免影响保研。

因此，笔者的建议是，如果对于转专业非常有信心，可以自己在大一下和大二上就修目标专业的相关课程。这样的行为也可以放在面试中当做自己的谈资。如果最终没转成，这部分课程就算个性化学分，也不会太大影响。

### （五）往年的一些情况

由于工科平台分流和评选奖学金的时间很接近，在2018级分流中，某学院曾经一度取消了转出学生的奖学金资格。后来学生据理力争，拿出学生手册上的规定，最终拿到了这部分奖学金。

在2017级分流中，部分专业在考核时不完全看学积分成绩，某同学原专业排名90%仍然成功转入。

在2016级分流中，某院某专业第一同学申请转专业被系里面卡着不放人，最后没能成功转专业。这个系卡转专业是有前科的，而相比之下每年转出近30人的另一学院就非常大度。

在2016级分流中，某同学在大二上学期通过了转专业考核，但是当学期挂了一门选修课，最终没能转专业成功。笔者尚不知晓其是不想转专业了故意挂了，还是真不幸挂了。

### （一）农学提前批

这里的农学提前批指的是入学方式为提前批的自然保护与环境生态类，并非自科班。笔者对此部分实际情况并不了解，仅仅引用农生学院的公告。

> 第一学年核心课程学积分排名在所在专业前 10%、无不及格课程的学生，经学生本人申请，可在学院植物科学与技术、动物科学、资源环境科学等 3 个专业内申请调整专业。

> 每位学生只能申请一个专业，每个专业招收学生人数为所在专业人数的10%，接收专业根据学生的学积分排名依次招收。

根据公告，这部分同学只能在3个专业中选择，而且对于学积分的要求比较苛刻。近几年主要在大二上9月份刚开学的时候进行申请和考核。

### （二）政策外转专业

对于转专业完全不受限制的类别，部分同学认为只有自主转专业的这一次机会。实际上满足其他条件仍然可以申请转专业，仅仅是不通过自主转专业这个渠道。笔者当年并未关注到这类转专业情况，后来知道有同学走了一遍这个流程，虽然未能转成，但是从中了解了一些情况。这部分在学生手册《上海交通大学本科生管理规定》（沪交教〔2019〕42号）第二十四条至第二十八条中有所说明，将其简单摘录如下：

> 第二十五条 （二）其他类别校内转专业学生，原则上学生高考成绩不得低于转入专业的高考录取分数线；同时学生本人应当提出书面申请，经学生所在学院主管院长和主管书记审核同意，在转入学院（专业）教学资源允许的情况下，经拟转入学院主管院长和主管书记审核同意后，报学校教务处和主管校长审批

> 第二十七条 其他类别转专业应该在春、秋学期开学后两周内完成所有手续的办理。

从文本字面意思上来说，假设一个经管类专业的学生想申请转入电院某专业，那么理论上他可以在大二上或者大二下开学两周内完成手续完成转专业。他需要在两个学院的教务办，以及学校的教务处之间来回跑。但是很多时候教务老师可能嫌麻烦，或者自己有事或者其他什么情况不给办或者拖延，就很难转成功。

### （三）参军退伍

如果自科、工科平台等转专业存在限制的同学，想跳出平台转其他专业，可以走参军这条路。根据学校相关说法，参军退伍的同学可以不受平台限制转专业，比如原来是自科试验班的专业，他可以选择申请转入电院计算机或者信安等专业。而且参军的其他待遇非常好，在保研、考研、落户等诸多政策上均有所支持，对于有这样想法的同学可以与思政联系。

但是要注意此政策可能会有变化，若是参军仅为转专业的话，在参军之前需要确认是否存在这一项规定。

### （一）综合评定

自主转专业中会用到一张《上海交通大学本科生自主调整专业类别综合评定表》，此表可以在每年教务处通知中下载。其中列举了教务处对于院系考核中可以使用的指标和建议考察内容，主要包括：

1. 高考成绩：生源地、高考成绩、省市排名
2. 学习成绩：学积分、专业排名
3. 选拔考试成绩：学院针对本工作特别组织的考试
4. 基础知识掌握情况：各科成绩
5. 外语能力：外语表达能力、外语证书
6. 综合素质：转专业原因、合作精神、政治表现、业余活动、获奖情况
7. 其他

当然此表仅仅为建议，院系可以根据自己的情况，自主设计指标、考察内容和分值。但是就无法知道院系究竟是怎么考察，各部分占比情况也无从得知。

对于工科、自科等平台，虽然教务处没有提供这样一张表，但是各院系在面试时确实在一张记录表上进行了记录。虽然不知道究竟考核了哪些内容、是否和自主转专业一致，但是笔者认为可以以此为参考。

### （二）笔试或者机考

部分专业存在笔试或者机考，而是否有笔试或者机考，考什么，怎么考，每年情况不一样。2016级自主转专业和工科平台转专业中，信息安全存在笔试，考C++，但是从2017级起信安取消了笔试。2016和2017级自主转专业中，计算机存在机考，但是从2017级工科平台分流起，计算机取消了机考，只保留面试。

这部分的具体情况需要读者自行前往各院系本科教务办网站进行查询。

### （三）面试

在面试的时候，面试的老师手上会有之前申请时填写的资料，包括成绩单、申请表等，但是不见得会人手一份。

很多同学会关心面试问什么。根据笔者为数不多的经验，以及了解到的情况，可能会有如下问题：

1. 自我介绍
2. 转专业原因
3. 询问成绩，比如排名或者某些课程分数不高
4. 是否有相关专业的学习/科研/比赛经历
5. 自我介绍或者转专业原因中提及的，让老师感兴趣的点
6. 如果是第二志愿，为什么会把这个专业放到第二志愿
7. 不排除专业知识问答

根据笔者的认识，面试主要考察的是学生和这个专业的匹配程度，包括是否有能力和潜力等等。因此，个人陈述时应该以“我为什么要选择这个专业”和“这个专业为什么要选择我”两个问题展开。上述第5点就需要同学在准备面试的时候，从个人陈述中主动埋下种子，主动吸引老师往预先准备的问题上询问，并非常自然地回答出老师们的提问。如果老师对于学生的陈述中看不到任何他感兴趣的地方，或许他就很难从众多的候选者中选择这个同学。

另外，很多院系面试的时候没有说让学生带材料。学生完全可以自己准备一些证书、奖状的材料，面试的时候交给老师翻阅，以显自己准备充足或非常优秀之意。

## 六、总结

最后总结一下，本文中关于政策方面的内容具有很强的时效性，部分内容可能对于部分年级/专业不适用，或者政策已经发生了变化。读者应自己根据当年情况进行取舍，笔者不承担任何因本文导致的转专业失败等责任。

这就是关于上海交大转专业的事情了，大家有什么想法呢，欢迎在评论区告诉小编一起讨论哦！

**Comment by brucechin** [comment]
已push
