### ISSUE TITLE
附录"上海交通大学CS生存指南--番外篇1"实习部分信息更新

### ISSUE THREAD

**Issue by songqun** [SurviveSJTU/SurviveSJTUManual#26]
附录"上海交通大学CS生存指南--番外篇"中的"13.实习与就业现状"内：

"还有一点需要注意，理论上实习生签的是劳务合同，需要交20%的税，在签合同的时候一定要问清楚hr是税前还是税后。"，这段内容需要更新。
https://github.com/SurviveSJTU/SurviveSJTUManual/blob/master/fu-lu/yi-jing-gong-zuo-xue-chang-de-ren-sheng-jing-yan/shang-hai-jiao-tong-da-xue-cs-sheng-cun-zhi-nan-fan-wai-pian-1.md

从2020年开始实习生工资已经按照个税来算，2019年不满6w收入的话可以全额退税。具体操作可以google一下"实习生 退税"。（本人19年实习的税已经操作成功退回来了）。之后具体实习生税怎么算（不满一定年收入能不能完全免税）我还没看到解读，但至少应该比以前的"800以外劳务税20%"要少得多。

**Comment by brucechin** [comment]
已修改，谢谢！
