### ISSUE TITLE
本科生转学经验分享-新加坡

### ISSUE THREAD

**Issue by Persdre** [SurviveSJTU/SurviveSJTUManual#27]
# 转学新加坡经验分享

> 成文时间：2020年5月8日

## 一、转学是什么？
转学即为在某所学校就读期间，换一所学校继续就读。在小学和中学阶段，转学司空见惯。其实大学阶段也是可以转学的，但是由于政策的限制，从交大转去其他中国大陆的学校几乎不可能。尽管《学生手册》上写如有合理理由可转至大陆其他高校，但每年能做到者寥寥无几。

好消息是，中国大陆以外的大学通常都接受转学生。交大的同学可以根据各学校官网的要求申请。

## 二、为什么要转学到新加坡？
大家比较熟悉的转学是转学至美国高校。得益于密歇根学院的2+2项目，一些密院学子了解到了美国高校的转学政策从而选择在大一/大二转学至美国。美国高校的优势在于其认可度高，且美国能够提供的高薪岗位较多。因此，像UMich, UIUC等top 30美国高校成为中国大陆转学同学的热门选择。

转学至新加坡与转学至美国有一些不同。新加坡最出名的两所大学NUS与NTU并不接受新加坡以外同学的转学申请，但是接受在读生以freshman的身份申请。能够转的学分也比较有限，不承认大多数非专业课，尤其是在大跨度改变专业的情况下。比较理想的情况是可以将大一上的公共专业课比如高等数学，大学物理等转学分。

新加坡的一大优势是离中国比较近，并且学费以及消费相对于美国而言都比较低。如果选择全额自费的话，每年的学费生活费加在一起大约25万人民币。如果愿意和新加坡政府签助学金协议（Tuition Grant)，那么每年的费用可以降到15万左右，条件是毕业后需立即在新加坡工作三年。新加坡还有针对于学生的学费贷款（Tuition Fee Loan)以及其他各种经济帮助（Financial Aid)。根据笔者和同学的交流，如果把能拿到的减免都拿到，那么一年的总费用可以降至8万左右。

新加坡是华人为主体的国家，且针对中国人的种族歧视较少。此外，新加坡以严刑峻法和良好的治安闻名。在生活方面较为安全，在饮食上与中国差别不大。对于偏好安稳，偏爱华人文化的同学们来说，新加坡的生活容易融入。

新加坡的NUS与NTU最近两年拿下了QS排名的亚洲第一高校，在本地以及在中国的认可度都很高。毕业生的出路不成问题，尤其是计算机专业。根据去年NUS的官方统计数据，计算机专业的本科毕业生的起薪中位数为五千新币（约两万五人民币）每月。

笔者个人的转学原因是希望在本科阶段能够学习计算机以及数学专业，但笔者并不符合交大内部的转专业要求。考虑到家庭的经济状况，新加坡的两所高校是比较好的选择。

## 三、如何转学至新加坡？
以下只针对于NUS/NTU的转学流程：

1. 准备相关材料

&emsp;这两所高校均要求申请者提供高考成绩单，中考成绩单，英语成绩（托福或者雅思）以及大学成绩单。建议语言成绩尽快考出来，可以利用暑假/寒假时间突击一到两个月后立刻考试，效果较好。高考成绩单需要省教育厅出具，需有公章，并且还需要公证处的公证。中考成绩单需要市教育局出具，需有公章，同样需要公证。这部分的材料需要提前准备。笔者当时拜托了在省会念书的同学帮忙弄到 了高考成绩单，拜托父母跑了市教育局很多回才办好中考成绩单，花费很多时间。

2. 准备面试

&emsp;在申请某些专业，比如法律时会有面试环节。通常会问申请者为什么选择这个专业，对未来有什么样的打算。对于跨专业的申请者来说，大概率会被问到为何不愿意继续就读原来的专业。对于这些问题并没有固定的答案，但回答的基调需要积极向上，不建议对原来的专业做负面的评价。

## 四、就读体验
&emsp;笔者目前在NUS就读，个人体验是这边的学习压力没有交大大，但是想要考出好的成绩同样需要付出很大的努力。周围的local们并没有知乎上说的那么水（看到过说他们是二本水平的）。因为新加坡政府一直在全亚洲搜罗尖子生给他们发奖学金让他们来读书，所以NUS有很多印度，马来西亚等国家的优秀同学。

&emsp;由于笔者来到NUS只有一年，所以在科研方面的了解并不算多。根据上课的体验来看，这里的大部分Prof的履历，教学能力都是很好的，大部分青年教师有藤校Phd的经历。

## 五、总结
新加坡是一个可以考虑的转学地点，尤其对于家庭经济条件不是特别好的同学来说。这篇分享只是笔者个人的经验，不是很严谨也不保证之后的转学政策不会改变。希望大家权衡利弊，深思熟虑之后再去转学。无论成功与否，这将是你人生中很难忘的一次经历。

**Comment by brucechin** [comment]
谢谢qian！
