### ISSUE TITLE
Seems no one is here...

### ISSUE THREAD

**Issue by einsteinliu** [SurviveSJTU/SurviveSJTUManual#32]
https://github.com/SurviveSJTU/SurviveSJTUManual/blob/master/fu-lu/ben-ke-sheng-zhuan-ye-jie-shao-todo/sheng-wu-yi-xue-gong-cheng-16-ji-tong-xue-fen-xiang.md

里面有一句话“国内生医工发展落后于国外，本科出来工作不好找，国外读个BME硕士不读博工作也不好找。"
国外的BME硕士如果方向和EE，CS相关的话工作好找的，可以补充说明一下。

不过总得来说写的还是很好的！

**Comment by einsteinliu** [comment]
不过总得来说写的还是很好的！

**Comment by brucechin** [comment]
已经针对您的意见做微修，谢谢！
