### ISSUE TITLE
关于 PR 和项目贡献

### ISSUE THREAD

**Issue by kongasa** [SurviveSJTU/SurviveSJTUManual#52]
项目根目录关于PR的介绍较为简略，使用 GitBook 操作设置也较为繁琐。建议增加使用 GitHub 自带的文档编辑功能，只需拥有 GitHub 账号并能与 GitHub 建立连接就可使用。它可以自动 fork 并创建 branch，具有效果预览功能，对非 Git 使用者较为友好。

**Comment by kongasa** [comment]
校园网对 GitHub 的链接不稳定，授权窗口经常打不开。是否考虑将项目迁移到更易访问的平台。

**Comment by brucechin** [comment]
抱歉回复晚了。使用GitHub自带的文档编辑不方便同时修改目录页，用gitbook确实有些繁琐。

**Comment by Sirlanri** [comment]
如果不用Git，可以把修改提交到issue，我们有时间会进行提交合并:)
