### ISSUE TITLE
PR：增加了对交大邮箱设置的提醒

### ISSUE THREAD

**Issue by Gainlos** [SurviveSJTU/SurviveSJTUManual#63]
因为很多同学（主要是我的亲身经历）在收到腾讯、字节等公司的面试通知时，该邮件会被扔到垃圾邮件中，导致同学们错过了面试的截至时间，希望在手册中加入对垃圾邮件设置的提醒。
在更改相关内容后我提了一次PR，请各位斧正。

**Comment by brucechin** [comment]
感谢！我已经merge这个PR，抱歉回复晚了。
