### ISSUE TITLE
指南授权请求

### ISSUE THREAD

**Issue by Mikachu2333** [SurviveSJTU/SurviveSJTUManual#79]
**尊敬的指南主编：**
　　您好！
　　我是山东第二医科大学的一位同学。在编写我校指南时，鄙人参考了贵编委所撰写指南的部分思想及项目结构（共约120字左右，鄙人项目全文约4.5w字），因我项目为 [CC-BY-SA-4.0 license](https://github.com/Mikachu2333/sdsmu_welcome_tex#CC-BY-SA-4.0-1-ov-file)，可能与贵编委的要求相悖（未找到能明确贵项目的LICENCE等相关说明），故特此咨询，以免产生可能的法律纠纷。
　　盼祷拔冗见告。

**LinkChou**

附：
指南地址：https://github.com/Mikachu2333/sdsmu_welcome_tex
指南pdf文件：见附件
[main.pdf](https://github.com/user-attachments/files/16392566/main.pdf)

**Comment by Mikachu2333** [comment]
因邮件未能得到回复而重开此issue

**Comment by brucechin** [comment]
可以的，我应该已经回复你邮件了。

**Comment by Mikachu2333** [comment]
非常感谢！
