### ISSUE TITLE
语言风格建议

### ISSUE THREAD

**Issue by dujiajun** [SurviveSJTU/SurviveSJTUManual#8]
新的访谈集系列的语言风格似乎和旧手册的风格差异较大，直接交错在一起似乎比较奇怪。
我的想法是能够对访谈集进行整理汇编，统一语言，而把原稿作为附录的形式。不知是否科学。

**Comment by brucechin** [comment]
可以安排，但估计要等到暑假了，现在先集中精力收够足够的投稿，比如院系介绍部分按专业整合到一起，出国申请/保研/考研等部分可以不用。
